[package]
name = "axum-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"  # Use the latest version of Axum
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["cors"] } # We'll need this later for CORS
